import vm from "node:vm";
import { describe, expect, it } from "vitest";
import {
  createRemovedChildSubscription,
  deriveNodePrefix,
  generateClashVergeScript,
  normalizeDomainSuffix,
  stableHash,
} from "../src/generator";
import type { GeneratorSpec } from "../src/types";

function baseSpec(overrides: Partial<GeneratorSpec> = {}): GeneratorSpec {
  return {
    targetProfile: {
      name: "fixture",
      source: "https://main.example.test/subscription",
    },
    parentGroupMode: "manual",
    parentGroupName: "PROXY",
    children: [
      {
        id: "one",
        groupName: "非AI出口",
        mode: "http",
        source: "https://subscription.example.test/key",
      },
    ],
    ai: {
      enabled: false,
      mode: "existing",
      groupName: "AI",
      customDomains: [],
    },
    ...overrides,
  };
}

function execute(script: string, config: Record<string, unknown>, profileName = "fixture") {
  const context: Record<string, unknown> = {};
  vm.createContext(context);
  vm.runInContext(`${script}\nthis.__main = main;`, context);
  return (context.__main as (value: Record<string, unknown>, profileName?: string) => Record<string, unknown>)(
    config,
    profileName,
  );
}

function parentConfig(extra: Record<string, unknown> = {}) {
  return {
    "proxy-groups": [{ name: "PROXY", type: "select", proxies: ["DIRECT"], ...extra }],
    rules: ["MATCH,PROXY"],
  };
}

function twoChildSpec(overrides: Partial<GeneratorSpec> = {}): GeneratorSpec {
  return baseSpec({
    children: [
      baseSpec().children[0],
      {
        id: "two",
        groupName: "赔钱机场",
        mode: "http",
        source: "https://second.example.test/private-key",
      },
    ],
    ...overrides,
  });
}

describe("Clash Verge extension script generator", () => {
  it("generates one HTTP provider, a dedicated group, and a masked preview", () => {
    const generated = generateClashVergeScript(baseSpec());
    expect(generated.valid).toBe(true);
    expect(generated.fullScript).toContain("https://subscription.example.test/key");
    expect(generated.maskedScript).not.toContain("subscription.example.test");
    expect(generated.maskedScript).toContain("https://••••••••••••");

    const output = execute(generated.fullScript, parentConfig());
    const providerKey = "非AI出口";
    const storageKey = `clash_verge_kit_${stableHash("provider:非AI出口")}`;
    const providers = output["proxy-providers"] as Record<string, Record<string, unknown>>;
    const groups = output["proxy-groups"] as Array<Record<string, unknown>>;
    expect(providers[providerKey].type).toBe("http");
    expect(providers[providerKey].path).toBe(`./proxy_providers/clash-verge-kit/${storageKey}.yaml`);
    expect(providers[providerKey].override).toBeUndefined();
    expect(groups.find((group) => group.name === "非AI出口")?.use).toEqual([providerKey]);
    expect((groups[0].proxies as string[])).toContain("非AI出口");
    expect(providers[storageKey]).toBeUndefined();
  });

  it("keeps the basic generated script concise without packing complex statements", () => {
    const generated = generateClashVergeScript(baseSpec());
    const lines = generated.fullScript.split("\n");

    expect(lines.length).toBeLessThanOrEqual(200);
    expect(lines.filter((line) => /}\s+(?:function|if|const|let|return|throw|SETTINGS|config\[)/.test(line)))
      .toEqual([]);
    expect(generated.fullScript).toContain("/* Generated by Clash Verge Kit; no file or network I/O. */");
  });

  it("blocks a nested subscription that resolves to the target profile source", () => {
    const generated = generateClashVergeScript(baseSpec({
      targetProfile: {
        name: "主订阅",
        source: "https://same.example.test/sub?token=redacted&client=one#ignored",
      },
      children: [{
        id: "self",
        groupName: "错误自嵌套",
        mode: "http",
        source: "https://same.example.test/sub?client=one&token=redacted",
      }],
    }));
    expect(generated.valid).toBe(false);
    expect(generated.diagnostics.some((item) => item.code === "self-nesting-source")).toBe(true);
    expect(generated.fullScript).toBe("");
  });

  it("rejects duplicate child sources after URL normalization", () => {
    const generated = generateClashVergeScript(baseSpec({
      children: [
        {
          id: "one",
          groupName: "子组一",
          mode: "http",
          source: "https://duplicate.example.test/sub?token=redacted&client=one#ignored",
        },
        {
          id: "two",
          groupName: "子组二",
          mode: "http",
          source: "https://duplicate.example.test/sub?client=one&token=redacted",
        },
      ],
    }));

    expect(generated.valid).toBe(false);
    expect(generated.diagnostics.some((item) => item.code === "duplicate-child-source")).toBe(true);
    expect(generated.fullScript).toBe("");
  });

  it("returns a diagnostic instead of throwing when more than 64 children are supplied", () => {
    let thrown: unknown;
    let generated: ReturnType<typeof generateClashVergeScript> | undefined;
    try {
      generated = generateClashVergeScript(baseSpec({
        children: Array.from({ length: 65 }, (_, index) => ({
          id: `child-${index + 1}`,
          groupName: `子组 ${index + 1}`,
          mode: "http" as const,
          source: `https://child-${index + 1}.example.test/subscription`,
        })),
      }));
    } catch (error) {
      thrown = error;
    }

    expect(thrown).toBeUndefined();
    expect(generated?.valid).toBe(false);
    expect(generated?.diagnostics.some((item) => item.code === "child-limit-exceeded")).toBe(true);
    expect(generated?.fullScript).toBe("");
  });

  it("returns a diagnostic instead of throwing when more than 64 removed children are supplied", () => {
    let thrown: unknown;
    let generated: ReturnType<typeof generateClashVergeScript> | undefined;
    try {
      generated = generateClashVergeScript(baseSpec({
        children: [],
        removedChildren: Array.from({ length: 65 }, (_, index) => createRemovedChildSubscription({
          groupName: `待移除子组 ${index + 1}`,
          mode: "http",
          source: `https://removed-${index + 1}.example.test/subscription`,
        })),
      }));
    } catch (error) {
      thrown = error;
    }

    expect(thrown).toBeUndefined();
    expect(generated?.valid).toBe(false);
    expect(generated?.diagnostics.some((item) => item.code === "removed-child-limit-exceeded")).toBe(true);
    expect(generated?.fullScript).toBe("");
  });

  it("runs only for the target profile and does not embed the target source", () => {
    const generated = generateClashVergeScript(baseSpec({
      targetProfile: {
        name: "唯一主订阅",
        source: "https://main.example.test/private-main-token",
      },
    }));
    expect(generated.valid).toBe(true);
    expect(generated.fullScript).toContain("唯一主订阅");
    expect(generated.fullScript).not.toContain("private-main-token");

    const config = parentConfig();
    const before = JSON.parse(JSON.stringify(config));
    const skipped = execute(generated.fullScript, config, "另一份订阅");
    expect(skipped).toEqual(before);
    expect(skipped).toBe(config);

    const applied = execute(generated.fullScript, parentConfig(), "唯一主订阅");
    expect(Object.keys(applied["proxy-providers"] as Record<string, unknown>)).toHaveLength(1);
  });

  it("auto-detects the select group targeted by the terminal MATCH rule", () => {
    const generated = generateClashVergeScript(
      baseSpec({ parentGroupMode: "auto", parentGroupName: "" }),
    );
    expect(generated.valid).toBe(true);
    expect(generated.topology.parentGroupMode).toBe("auto");

    const config = {
      "proxy-groups": [
        { name: "备用选择", type: "select", proxies: ["DIRECT"] },
        { name: "主出口", type: "select", proxies: ["DIRECT"] },
      ],
      rules: ["DOMAIN,example.com,DIRECT", "MATCH,主出口"],
    };
    const output = execute(generated.fullScript, config);
    const groups = output["proxy-groups"] as Array<Record<string, unknown>>;
    expect(groups.find((group) => group.name === "主出口")?.proxies).toEqual(["DIRECT", "非AI出口"]);
    expect(groups.find((group) => group.name === "备用选择")?.proxies).toEqual(["DIRECT"]);
  });

  it("auto-detects the only available select group without terminal rules", () => {
    const generated = generateClashVergeScript(
      baseSpec({ parentGroupMode: "auto", parentGroupName: "" }),
    );
    const output = execute(generated.fullScript, {
      "proxy-groups": [
        { name: "自动测速", type: "url-test", proxies: [] },
        { name: "唯一手选", type: "select", proxies: ["DIRECT"] },
      ],
      rules: [],
    });
    const groups = output["proxy-groups"] as Array<Record<string, unknown>>;
    expect(groups.find((group) => group.name === "唯一手选")?.proxies).toEqual(["DIRECT", "非AI出口"]);
  });

  it("stops without mutation when automatic parent detection is ambiguous", () => {
    const generated = generateClashVergeScript(
      baseSpec({ parentGroupMode: "auto", parentGroupName: "" }),
    );
    const config = {
      "proxy-groups": [
        { name: "选择一", type: "select", proxies: ["DIRECT"] },
        { name: "选择二", type: "select", proxies: ["DIRECT"] },
      ],
      rules: [],
    };
    const before = JSON.parse(JSON.stringify(config));
    expect(() => execute(generated.fullScript, config)).toThrow(/选择一.*选择二.*手动指定/);
    expect(config).toEqual(before);
  });

  it("supports multiple mixed HTTP and file providers", () => {
    const generated = generateClashVergeScript(
      baseSpec({
        children: [
          baseSpec().children[0],
          { id: "two", groupName: "本地备用", mode: "file", source: "./profiles/backup.yaml" },
        ],
      }),
    );
    expect(generated.valid).toBe(true);
    const output = execute(generated.fullScript, parentConfig());
    const providers = Object.values(output["proxy-providers"] as Record<string, Record<string, unknown>>);
    expect(providers.map((provider) => provider.type).sort()).toEqual(["file", "http"]);
    expect(providers.find((provider) => provider.type === "file")?.path).toBe("./profiles/backup.yaml");
    const parent = (output["proxy-groups"] as Array<Record<string, unknown>>)[0];
    expect(parent.proxies).toEqual(["DIRECT", "非AI出口", "本地备用"]);
  });

  it("is idempotent when the generated script runs repeatedly", () => {
    const generated = generateClashVergeScript(baseSpec());
    const first = execute(generated.fullScript, parentConfig({ "include-all": true }));
    const second = execute(generated.fullScript, first);
    const groups = second["proxy-groups"] as Array<Record<string, unknown>>;
    const parent = groups.find((group) => group.name === "PROXY")!;
    expect(groups.filter((group) => group.name === "非AI出口")).toHaveLength(1);
    expect((parent.proxies as string[]).filter((name) => name === "非AI出口")).toHaveLength(1);
    expect(String(parent["exclude-filter"]).split("`")).toHaveLength(1);
  });

  it("generates a replacement script that keeps one child and safely removes another", () => {
    const originalSpec = twoChildSpec();
    const config = execute(
      generateClashVergeScript(originalSpec).fullScript,
      parentConfig({ "include-all": true, "exclude-filter": "USER_FILTER" }),
    );
    const removed = originalSpec.children[1]!;
    const update = generateClashVergeScript({
      ...originalSpec,
      children: [originalSpec.children[0]!],
      removedChildren: [createRemovedChildSubscription(removed)],
    });

    expect(update.valid).toBe(true);
    expect(update.operation).toBe("update");
    expect(update.topology.keptCount).toBe(1);
    expect(update.topology.removedCount).toBe(1);
    expect(update.fullScript).not.toContain(removed.source);

    const output = execute(update.fullScript, config);
    const groups = output["proxy-groups"] as Array<Record<string, unknown>>;
    const providers = output["proxy-providers"] as Record<string, unknown>;
    const parent = groups.find((group) => group.name === "PROXY")!;
    expect(groups.find((group) => group.name === "赔钱机场")).toBeUndefined();
    expect(groups.find((group) => group.name === "非AI出口")).toBeDefined();
    expect(providers["赔钱机场"]).toBeUndefined();
    expect(providers["非AI出口"]).toBeDefined();
    expect(parent.proxies).toEqual(["DIRECT", "非AI出口"]);
    expect(String(parent["exclude-filter"])).toContain("USER_FILTER");
    expect(String(parent["exclude-filter"])).toContain("\\[非AI出口\\] ");
    expect(String(parent["exclude-filter"])).not.toContain("\\[赔钱机场\\] ");
  });

  it("fully restores nested subscriptions while preserving unrelated configuration objects", () => {
    const originalSpec = twoChildSpec();
    const rules = ["DOMAIN,example.com,DIRECT", "MATCH,PROXY"];
    const dns = { enable: true, nameserver: ["https://dns.example.test/dns-query"] };
    const ruleProviders = { private: { type: "file", path: "./rules/private.yaml" } };
    const unrelatedProvider = { type: "file", path: "./profiles/unrelated.yaml" };
    const unrelatedGroup = { name: "原有测速", type: "url-test", proxies: ["DIRECT"] };
    const config = parentConfig({ "include-all": true }) as Record<string, unknown>;
    config.rules = rules;
    config.dns = dns;
    config["rule-providers"] = ruleProviders;
    config["proxy-providers"] = { unrelated: unrelatedProvider };
    (config["proxy-groups"] as Array<Record<string, unknown>>).push(unrelatedGroup);
    const applied = execute(generateClashVergeScript(originalSpec).fullScript, config);

    const restore = generateClashVergeScript({
      ...originalSpec,
      children: [],
      removedChildren: originalSpec.children.map(createRemovedChildSubscription),
    });
    expect(restore.operation).toBe("restore");
    expect(restore.fullScript).not.toContain("subscription.example.test/key");
    expect(restore.fullScript).not.toContain("second.example.test/private-key");

    const output = execute(restore.fullScript, applied);
    const groups = output["proxy-groups"] as Array<Record<string, unknown>>;
    const providers = output["proxy-providers"] as Record<string, unknown>;
    const parent = groups.find((group) => group.name === "PROXY")!;
    expect(groups.map((group) => group.name)).toEqual(["PROXY", "原有测速"]);
    expect(parent.proxies).toEqual(["DIRECT"]);
    expect(parent["exclude-filter"]).toBeUndefined();
    expect(Object.keys(providers)).toEqual(["unrelated"]);
    expect(output.rules).toBe(rules);
    expect(output.dns).toBe(dns);
    expect(output["rule-providers"]).toBe(ruleProviders);
    expect(providers.unrelated).toBe(unrelatedProvider);
    expect(groups.find((group) => group.name === "原有测速")).toBe(unrelatedGroup);

    const repeated = execute(restore.fullScript, output);
    expect(repeated).toEqual(output);
  });

  it("keeps generated AI routing when all nested subscriptions are restored", () => {
    const originalSpec = baseSpec({
      ai: { enabled: true, mode: "create", groupName: "AI 自动", customDomains: ["openai.com"] },
    });
    const applied = execute(generateClashVergeScript(originalSpec).fullScript, parentConfig());
    const restore = generateClashVergeScript({
      ...originalSpec,
      children: [],
      removedChildren: originalSpec.children.map(createRemovedChildSubscription),
    });
    const first = execute(restore.fullScript, applied);
    const second = execute(restore.fullScript, first);
    const groups = second["proxy-groups"] as Array<Record<string, unknown>>;
    const rules = second.rules as string[];
    expect(groups.find((group) => group.name === "非AI出口")).toBeUndefined();
    expect(groups.filter((group) => group.name === "AI 自动")).toHaveLength(1);
    expect(rules.filter((rule) => rule === "DOMAIN-SUFFIX,openai.com,AI 自动")).toHaveLength(1);
    expect(rules.filter((rule) => rule.startsWith("RULE-SET,clash_verge_kit_ai_"))).toHaveLength(1);
    expect(Object.keys(second["rule-providers"] as Record<string, unknown>)).toHaveLength(1);
  });

  it("prunes child creation helpers from a full restore script", () => {
    const originalSpec = twoChildSpec();
    const restoreScript = generateClashVergeScript({
      ...originalSpec,
      children: [],
      removedChildren: originalSpec.children.map(createRemovedChildSubscription),
    }).fullScript;

    expect(restoreScript).not.toContain("ensureChildProvider");
    expect(restoreScript).not.toContain("ensureChildGroup");
    expect(restoreScript).not.toContain("providerForParent");
    expect(restoreScript.length).toBeLessThan(9_000);
  });

  it("stops before mutation when another group references a child selected for removal", () => {
    const originalSpec = baseSpec();
    const restore = generateClashVergeScript({
      ...originalSpec,
      children: [],
      removedChildren: originalSpec.children.map(createRemovedChildSubscription),
    });
    const config = execute(generateClashVergeScript(originalSpec).fullScript, parentConfig());
    (config["proxy-groups"] as Array<Record<string, unknown>>).push({
      name: "外部手动组",
      type: "select",
      proxies: ["非AI出口"],
    });
    const before = JSON.parse(JSON.stringify(config));
    expect(() => execute(restore.fullScript, config)).toThrow(/其他代理组仍引用待移除子组/);
    expect(config).toEqual(before);
  });

  it("stops before mutation when another group uses the managed provider or its source was changed", () => {
    const originalSpec = baseSpec();
    const restore = generateClashVergeScript({
      ...originalSpec,
      children: [],
      removedChildren: originalSpec.children.map(createRemovedChildSubscription),
    });
    const referenced = execute(generateClashVergeScript(originalSpec).fullScript, parentConfig());
    (referenced["proxy-groups"] as Array<Record<string, unknown>>).push({
      name: "外部 provider 组",
      type: "select",
      use: ["非AI出口"],
    });
    const referencedBefore = JSON.parse(JSON.stringify(referenced));
    expect(() => execute(restore.fullScript, referenced)).toThrow(/仍引用待移除代理提供者/);
    expect(referenced).toEqual(referencedBefore);

    const tampered = execute(generateClashVergeScript(originalSpec).fullScript, parentConfig());
    (tampered["proxy-providers"] as Record<string, Record<string, unknown>>)["非AI出口"]!.url =
      "https://tampered.example.test/sub";
    const tamperedBefore = JSON.parse(JSON.stringify(tampered));
    expect(() => execute(restore.fullScript, tampered)).toThrow(/来源不匹配/);
    expect(tampered).toEqual(tamperedBefore);
  });

  it("removes a safely owned legacy Clash Verge Kit provider and is idempotent", () => {
    const originalSpec = baseSpec();
    const child = originalSpec.children[0]!;
    const removal = createRemovedChildSubscription(child);
    const config = parentConfig() as Record<string, unknown>;
    const parent = (config["proxy-groups"] as Array<Record<string, unknown>>)[0]!;
    (parent.proxies as string[]).push(child.groupName);
    config["proxy-providers"] = {
      [removal.legacyProviderKey]: {
        type: "http",
        url: child.source,
        path: `./proxy_providers/clash-verge-kit/${removal.legacyProviderKey}.yaml`,
      },
    };
    (config["proxy-groups"] as Array<Record<string, unknown>>).push({
      name: child.groupName,
      type: "select",
      use: [removal.legacyProviderKey],
    });
    const restore = generateClashVergeScript({
      ...originalSpec,
      children: [],
      removedChildren: [removal],
    });
    const first = execute(restore.fullScript, config);
    const second = execute(restore.fullScript, first);
    expect(second).toEqual(first);
    expect((second["proxy-groups"] as Array<Record<string, unknown>>).map((group) => group.name)).toEqual(["PROXY"]);
    expect(second["proxy-providers"]).toEqual({});
  });

  it("excludes every nested prefix from include-all parent groups", () => {
    const spec = baseSpec({
      children: [
        baseSpec().children[0],
        { id: "two", groupName: "备用", mode: "file", source: "./profiles/backup.yml" },
      ],
    });
    const output = execute(generateClashVergeScript(spec).fullScript, parentConfig({ "include-all": true }));
    const parent = (output["proxy-groups"] as Array<Record<string, unknown>>)[0];
    const filter = String(parent["exclude-filter"]);
    expect(filter).toContain("\\[非AI出口\\] ");
    expect(filter).toContain("\\[备用\\] ");
    const providers = output["proxy-providers"] as Record<string, Record<string, unknown>>;
    expect((providers["非AI出口"].override as Record<string, unknown>)["additional-prefix"])
      .toBe(deriveNodePrefix("非AI出口"));
  });

  it("throws before mutation when the parent is missing or not select", () => {
    const script = generateClashVergeScript(baseSpec()).fullScript;
    expect(() => execute(script, { "proxy-groups": [], rules: [] })).toThrow(/未找到主代理组/);
    expect(() =>
      execute(script, { "proxy-groups": [{ name: "PROXY", type: "url-test" }], rules: [] }),
    ).toThrow(/select/);
  });

  it("rejects group collisions, unsafe paths, and provider key conflicts", () => {
    expect(
      generateClashVergeScript(baseSpec({ children: [{ ...baseSpec().children[0], groupName: "PROXY" }] })).valid,
    ).toBe(false);
    expect(
      generateClashVergeScript(
        baseSpec({ children: [{ id: "bad", groupName: "Bad", mode: "file", source: "./profiles/../secret.yaml" }] }),
      ).valid,
    ).toBe(false);
    expect(
      generateClashVergeScript(
        baseSpec({ children: [baseSpec().children[0], { ...baseSpec().children[0], id: "two" }] }),
      ).valid,
    ).toBe(false);

    const config = parentConfig() as Record<string, unknown>;
    config["proxy-providers"] = { 非AI出口: { type: "http", url: "https://other.invalid" } };
    expect(() => execute(generateClashVergeScript(baseSpec()).fullScript, config)).toThrow(/键冲突/);
  });

  it("migrates a safely managed legacy provider key to the readable child name", () => {
    const legacyProviderKey = `clash_verge_kit_${stableHash("provider:非AI出口")}`;
    const config = parentConfig() as Record<string, unknown>;
    config["proxy-providers"] = {
      [legacyProviderKey]: {
        type: "http",
        url: "https://subscription.example.test/key",
        path: `./proxy_providers/clash-verge-kit/${legacyProviderKey}.yaml`,
      },
    };
    (config["proxy-groups"] as Array<Record<string, unknown>>).push({
      name: "非AI出口",
      type: "select",
      use: [legacyProviderKey],
    });

    const output = execute(generateClashVergeScript(baseSpec()).fullScript, config);
    const providers = output["proxy-providers"] as Record<string, Record<string, unknown>>;
    const group = (output["proxy-groups"] as Array<Record<string, unknown>>)
      .find((item) => item.name === "非AI出口");
    expect(providers[legacyProviderKey]).toBeUndefined();
    expect(providers["非AI出口"]).toBeDefined();
    expect(group?.use).toEqual(["非AI出口"]);
  });

  it("uses JSON serialization for malicious strings without executing them", () => {
    const groupName = 'Safe"; globalThis.__pwned = true; //';
    const spec = baseSpec({
      children: [
        {
          id: "attack",
          groupName,
          mode: "http",
          source: 'https://example.test/?value=";globalThis.__pwned=true;//',
        },
      ],
    });
    const generated = generateClashVergeScript(spec);
    expect(generated.valid).toBe(true);
    const context: Record<string, unknown> = { __pwned: false };
    vm.createContext(context);
    vm.runInContext(`${generated.fullScript}\nthis.__main = main;`, context);
    (context.__main as (value: Record<string, unknown>, profileName: string) => unknown)(
      parentConfig(),
      "fixture",
    );
    expect(context.__pwned).toBe(false);
  });

  it("leaves unrelated routing, DNS, providers, and groups untouched when AI is disabled", () => {
    const rules = ["DOMAIN,example.com,DIRECT", "MATCH,PROXY"];
    const dns = { enable: true, nameserver: ["https://dns.example.test/dns-query"] };
    const ruleProviders = {
      private: { type: "http", behavior: "domain", url: "https://rules.example.test/private.mrs" },
    };
    const existingProvider = { type: "file", path: "./profiles/existing.yaml" };
    const unrelatedGroup = { name: "原有测速", type: "url-test", proxies: ["DIRECT"], interval: 300 };
    const config = parentConfig() as Record<string, unknown>;
    config.rules = rules;
    config.dns = dns;
    config["rule-providers"] = ruleProviders;
    config["proxy-providers"] = { existing: existingProvider };
    (config["proxy-groups"] as Array<Record<string, unknown>>).push(unrelatedGroup);
    const output = execute(generateClashVergeScript(baseSpec()).fullScript, config);
    expect(output.rules).toBe(rules);
    expect(output.dns).toBe(dns);
    expect(output["rule-providers"]).toBe(ruleProviders);
    expect((output["proxy-providers"] as Record<string, unknown>).existing).toBe(existingProvider);
    expect((output["proxy-groups"] as Array<Record<string, unknown>>).find((group) => group.name === "原有测速"))
      .toBe(unrelatedGroup);
  });

  it("prunes AI and routing code from a manual pure-nesting script", () => {
    const script = generateClashVergeScript(baseSpec()).fullScript;
    expect(script).not.toContain("config.rules");
    expect(script).not.toContain("rule-providers");
    expect(script).not.toContain("SETTINGS.ai");
    expect(script.length).toBeLessThan(8_000);
  });

  it("prepends normalized custom domains before the remote AI ruleset for an existing group", () => {
    const spec = baseSpec({
      ai: {
        enabled: true,
        mode: "existing",
        groupName: "AI",
        customDomains: ["*.OpenAI.com", "+.anthropic.com", "openai.com"],
      },
    });
    const config = parentConfig() as Record<string, unknown>;
    (config["proxy-groups"] as Array<Record<string, unknown>>).push({ name: "AI", type: "select", proxies: ["DIRECT"] });
    const output = execute(generateClashVergeScript(spec).fullScript, config);
    const rules = output.rules as string[];
    expect(rules[0]).toBe("DOMAIN-SUFFIX,openai.com,AI");
    expect(rules[1]).toBe("DOMAIN-SUFFIX,anthropic.com,AI");
    expect(rules[2]).toMatch(/^RULE-SET,clash_verge_kit_ai_/);
    expect(rules[3]).toBe("MATCH,PROXY");
    expect(Object.values(output["rule-providers"] as Record<string, Record<string, unknown>>)[0].format).toBe("mrs");
  });

  it("creates an AI group from the parent's original sources without loops", () => {
    const spec = baseSpec({
      ai: { enabled: true, mode: "create", groupName: "AI 自动", customDomains: [] },
    });
    const config = parentConfig({ "include-all": true, use: ["main_provider"] }) as Record<string, unknown>;
    config["proxy-providers"] = { main_provider: { type: "file", path: "./profiles/main.yaml" } };
    const generated = generateClashVergeScript(spec);
    const first = execute(generated.fullScript, config);
    const second = execute(generated.fullScript, first);
    const groups = second["proxy-groups"] as Array<Record<string, unknown>>;
    const aiGroup = groups.find((group) => group.name === "AI 自动")!;
    expect(aiGroup.proxies).toEqual(["DIRECT"]);
    expect(aiGroup.use).toEqual(["main_provider"]);
    expect(aiGroup.proxies).not.toContain("非AI出口");
    expect(aiGroup.proxies).not.toContain("AI 自动");
    expect(String(aiGroup["exclude-filter"])).toContain("\\[非AI出口\\] ");
    expect(groups.filter((group) => group.name === "AI 自动")).toHaveLength(1);
    expect((second.rules as string[]).filter((rule) => rule.startsWith("RULE-SET,"))).toHaveLength(1);
  });

  it("normalizes international domains and rejects URLs and IP addresses", () => {
    expect(normalizeDomainSuffix("*.例子.测试")).toBe("xn--fsqu00a.xn--0zwm56d");
    expect(normalizeDomainSuffix("https://openai.com/path")).toBeNull();
    expect(normalizeDomainSuffix("127.0.0.1")).toBeNull();
  });
});
